/* This file is part of the cnspy(1.0).
 * Copyright (C) 2023 Shanghai Jiao Tong University and Authors.
 * Contact: Bo Zhang <zilpher@sjtu.edu.cn>
 * Licensed under the <MPL-2.0>;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at <https://www.mozilla.org/en-US/MPL/2.0/>.
 */

#include "threebody.h"
#define _prec 406
#define _order 211
int main(int argc, char *argv[]){
	tsm_init();
	tsm_clock_start();
	FILE *fp=fopen("../ans/result_threebody.txt","w");
	int i, j, order;
	order = _order;
	mpfr_t x_0[order+1], x_1[order+1], x_2[order+1], x_3[order+1], x_4[order+1], x_5[order+1], x_6[order+1], x_7[order+1], x_8[order+1], x_9[order+1], x_10[order+1], x_11[order+1], x_12[order+1], x_13[order+1], x_14[order+1], x_15[order+1], x_16[order+1], x_17[order+1];
	mpfr_t saver_0[order+1], saver_1[order+1], saver_2[order+1], saver_3[order+1], saver_4[order+1], saver_5[order+1], saver_6[order+1], saver_7[order+1], saver_8[order+1], saver_9[order+1], saver_10[order+1], saver_11[order+1], saver_12[order+1], saver_13[order+1], saver_14[order+1], saver_15[order+1], saver_16[order+1], saver_17[order+1], saver_18[order+1], saver_19[order+1], saver_20[order+1], saver_21[order+1], saver_22[order+1], saver_23[order+1], saver_24[order+1], saver_25[order+1], saver_26[order+1], saver_27[order+1], saver_28[order+1], saver_29[order+1], saver_30[order+1], saver_31[order+1], saver_32[order+1], saver_33[order+1], saver_34[order+1], saver_35[order+1], saver_36[order+1], saver_37[order+1], saver_38[order+1], saver_39[order+1], saver_40[order+1], saver_41[order+1], saver_42[order+1], saver_43[order+1], saver_44[order+1], saver_45[order+1], saver_46[order+1], saver_47[order+1], saver_48[order+1], saver_49[order+1], saver_50[order+1], saver_51[order+1], saver_52[order+1], saver_53[order+1], saver_54[order+1], saver_55[order+1], saver_56[order+1], saver_57[order+1], saver_58[order+1], saver_59[order+1], saver_60[order+1], saver_61[order+1], saver_62[order+1], saver_63[order+1], saver_64[order+1], saver_65[order+1], saver_66[order+1], saver_67[order+1], saver_68[order+1], saver_69[order+1], saver_70[order+1], saver_71[order+1], saver_72[order+1], saver_73[order+1], saver_74[order+1], saver_75[order+1], saver_76[order+1], saver_77[order+1], saver_78[order+1], saver_79[order+1], saver_80[order+1], saver_81[order+1], saver_82[order+1], saver_83[order+1], saver_84[order+1], saver_85[order+1], saver_86[order+1], saver_87[order+1], saver_88[order+1], saver_89[order+1], saver_90[order+1], saver_91[order+1], saver_92[order+1], saver_93[order+1], saver_94[order+1], saver_95[order+1], saver_96[order+1], saver_97[order+1], saver_98[order+1], saver_99[order+1], saver_100[order+1], saver_101[order+1], saver_102[order+1], saver_103[order+1], saver_104[order+1];
	mpfr_t constant_0, constant_1, constant_2, constant_3;
	mpfr_t t[order+1];
	mpfr_t inc_time, final_time;
	mpfr_t x_0_p, x_1_p, x_2_p, x_3_p, x_4_p, x_5_p, x_6_p, x_7_p, x_8_p, x_9_p, x_10_p, x_11_p, x_12_p, x_13_p, x_14_p, x_15_p, x_16_p, x_17_p;
	mpfr_inits2(_prec, inc_time, final_time, (mpfr_ptr) 0);
	mpfr_inits2(_prec, x_0_p, x_1_p, x_2_p, x_3_p, x_4_p, x_5_p, x_6_p, x_7_p, x_8_p, x_9_p, x_10_p, x_11_p, x_12_p, x_13_p, x_14_p, x_15_p, x_16_p, x_17_p, constant_0, constant_1, constant_2, constant_3, (mpfr_ptr) 0);
	for(i=0; i<order+1; i++){
		mpfr_inits2(_prec, t[i], x_0[i], x_1[i], x_2[i], x_3[i], x_4[i], x_5[i], x_6[i], x_7[i], x_8[i], x_9[i], x_10[i], x_11[i], x_12[i], x_13[i], x_14[i], x_15[i], x_16[i], x_17[i], saver_0[i], saver_1[i], saver_2[i], saver_3[i], saver_4[i], saver_5[i], saver_6[i], saver_7[i], saver_8[i], saver_9[i], saver_10[i], saver_11[i], saver_12[i], saver_13[i], saver_14[i], saver_15[i], saver_16[i], saver_17[i], saver_18[i], saver_19[i], saver_20[i], saver_21[i], saver_22[i], saver_23[i], saver_24[i], saver_25[i], saver_26[i], saver_27[i], saver_28[i], saver_29[i], saver_30[i], saver_31[i], saver_32[i], saver_33[i], saver_34[i], saver_35[i], saver_36[i], saver_37[i], saver_38[i], saver_39[i], saver_40[i], saver_41[i], saver_42[i], saver_43[i], saver_44[i], saver_45[i], saver_46[i], saver_47[i], saver_48[i], saver_49[i], saver_50[i], saver_51[i], saver_52[i], saver_53[i], saver_54[i], saver_55[i], saver_56[i], saver_57[i], saver_58[i], saver_59[i], saver_60[i], saver_61[i], saver_62[i], saver_63[i], saver_64[i], saver_65[i], saver_66[i], saver_67[i], saver_68[i], saver_69[i], saver_70[i], saver_71[i], saver_72[i], saver_73[i], saver_74[i], saver_75[i], saver_76[i], saver_77[i], saver_78[i], saver_79[i], saver_80[i], saver_81[i], saver_82[i], saver_83[i], saver_84[i], saver_85[i], saver_86[i], saver_87[i], saver_88[i], saver_89[i], saver_90[i], saver_91[i], saver_92[i], saver_93[i], saver_94[i], saver_95[i], saver_96[i], saver_97[i], saver_98[i], saver_99[i], saver_100[i], saver_101[i], saver_102[i], saver_103[i], saver_104[i], (mpfr_ptr) 0);
	}
	mpfr_set_str(final_time, "1000", 10, GMP_RNDN);
	mpfr_set_str(inc_time, "0.01", 10, GMP_RNDN);
	for(i=0; i<order+1; i++){
		mpfr_set_str(t[i], "0.0", 10, GMP_RNDN);
	}
	mpfr_set_str(constant_0, "2.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", 10, GMP_RNDN);
	mpfr_set_str(constant_1, "-1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", 10, GMP_RNDN);
	mpfr_set_str(constant_2, "-1.50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", 10, GMP_RNDN);
	mpfr_set_str(constant_3, "1.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", 10, GMP_RNDN);
	mpfr_set_str(t[0], "0", 10, GMP_RNDN);
	mpfr_set_str(t[1], "1.0", 10, GMP_RNDN);
	mpfr_set_str(x_0_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_1_p, "1e-60", 10, GMP_RNDN);
	mpfr_set_str(x_2_p, "-1", 10, GMP_RNDN);
	mpfr_set_str(x_3_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_4_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_5_p, "-1", 10, GMP_RNDN);
	mpfr_set_str(x_6_p, "1", 10, GMP_RNDN);
	mpfr_set_str(x_7_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_8_p, "1", 10, GMP_RNDN);
	mpfr_set_str(x_9_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_10_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_11_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_12_p, "-1", 10, GMP_RNDN);
	mpfr_set_str(x_13_p, "-1e-60", 10, GMP_RNDN);
	mpfr_set_str(x_14_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_15_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_16_p, "0", 10, GMP_RNDN);
	mpfr_set_str(x_17_p, "1", 10, GMP_RNDN);
	int fprint_flag=1;
	mpfr_t print_time, print_time_inc, fake_time;
	mpfr_inits2(_prec, print_time, print_time_inc, fake_time, (mpfr_ptr) 0);
	mpfr_set_str(print_time, "0.1", 10, GMP_RNDN);
	mpfr_set_str(print_time_inc, "0.1", 10, GMP_RNDN);
	mpfr_set_str(fake_time, "0.0", 10, GMP_RNDN);
	mpfr_t tol, max_Mm1, max_M, max_M0, one, dotseven, abs_tmp_1, abs_tmp_2, rhom_1 ,rhom_2, rhom;
	mpfr_inits2(_prec, tol, max_Mm1, max_M, max_M0, one, dotseven, abs_tmp_1, abs_tmp_2, rhom_1 ,rhom_2, rhom, (mpfr_ptr) 0);
	mpfr_set_str(one, "1.0", 10, GMP_RNDN);
	mpfr_set_str(dotseven, "0.7", 10, GMP_RNDN);
	int PRE=_prec;
	double delta_T=5, remaining_T=500, gamma=1.4, lyap=0.1681;
	int m=0;
	double print_time_d, T_s, T_c;
	print_time_d = mpfr_get_d(print_time,GMP_RNDN);
	T_s = m*print_time_d;
	T_c = mpfr_get_d(final_time,GMP_RNDN);
	while (mpfr_less_p(t[0], final_time)){
		if (fprint_flag && m%(int)(delta_T/print_time_d)==0 && m<=(int)((T_c-remaining_T)/print_time_d)){
			PRE=(int)ceil(gamma*lyap*(T_c-T_s)/log(10.0));
				order=(int)ceil(-0.001579568162499792*PRE*PRE+1.8177453190778905*PRE+8.319807166901247);
			mpfr_set_str(tol,"10.0",10,GMP_RNDN);
			mpfr_pow_si(tol, tol, -PRE, GMP_RNDN);
			PRE = (int)ceil(log2(10)*PRE)+1;
			tsm_change_prec(PRE);
			for(i=0; i<order+1; i++){
				mpfr_prec_round(t[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_0[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_1[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_2[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_3[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_4[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_5[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_6[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_7[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_8[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_9[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_10[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_11[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_12[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_13[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_14[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_15[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_16[i], PRE, GMP_RNDN);
				mpfr_prec_round(x_17[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_0[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_1[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_2[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_3[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_4[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_5[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_6[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_7[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_8[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_9[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_10[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_11[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_12[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_13[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_14[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_15[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_16[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_17[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_18[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_19[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_20[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_21[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_22[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_23[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_24[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_25[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_26[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_27[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_28[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_29[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_30[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_31[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_32[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_33[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_34[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_35[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_36[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_37[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_38[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_39[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_40[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_41[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_42[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_43[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_44[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_45[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_46[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_47[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_48[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_49[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_50[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_51[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_52[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_53[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_54[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_55[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_56[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_57[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_58[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_59[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_60[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_61[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_62[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_63[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_64[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_65[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_66[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_67[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_68[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_69[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_70[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_71[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_72[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_73[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_74[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_75[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_76[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_77[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_78[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_79[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_80[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_81[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_82[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_83[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_84[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_85[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_86[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_87[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_88[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_89[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_90[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_91[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_92[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_93[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_94[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_95[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_96[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_97[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_98[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_99[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_100[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_101[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_102[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_103[i], PRE, GMP_RNDN);
				mpfr_prec_round(saver_104[i], PRE, GMP_RNDN);
			}
			mpfr_prec_round(tol,PRE,GMP_RNDN);
			mpfr_prec_round(inc_time,PRE,GMP_RNDN);
			mpfr_prec_round(max_Mm1,PRE,GMP_RNDN);
			mpfr_prec_round(max_M,PRE,GMP_RNDN);
			mpfr_prec_round(max_M0,PRE,GMP_RNDN);
			mpfr_prec_round(one,PRE,GMP_RNDN);
			mpfr_prec_round(abs_tmp_1,PRE,GMP_RNDN);
			mpfr_prec_round(abs_tmp_2,PRE,GMP_RNDN);
			mpfr_prec_round(rhom_1,PRE,GMP_RNDN);
			mpfr_prec_round(rhom_2,PRE,GMP_RNDN);
			mpfr_prec_round(rhom,PRE,GMP_RNDN);
			mpfr_prec_round(print_time,PRE,GMP_RNDN);
			mpfr_prec_round(fake_time,PRE,GMP_RNDN);
			mpfr_prec_round(final_time,PRE,GMP_RNDN);
			mpfr_prec_round(x_0_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_1_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_2_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_3_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_4_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_5_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_6_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_7_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_8_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_9_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_10_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_11_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_12_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_13_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_14_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_15_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_16_p,PRE,GMP_RNDN);
			mpfr_prec_round(x_17_p,PRE,GMP_RNDN);
			mpfr_prec_round(constant_0,PRE,GMP_RNDN);
			mpfr_prec_round(constant_1,PRE,GMP_RNDN);
			mpfr_prec_round(constant_2,PRE,GMP_RNDN);
			mpfr_prec_round(constant_3,PRE,GMP_RNDN);
		}
		mpfr_set(x_0[0],x_0_p,GMP_RNDN);
		mpfr_set(x_1[0],x_1_p,GMP_RNDN);
		mpfr_set(x_2[0],x_2_p,GMP_RNDN);
		mpfr_set(x_3[0],x_3_p,GMP_RNDN);
		mpfr_set(x_4[0],x_4_p,GMP_RNDN);
		mpfr_set(x_5[0],x_5_p,GMP_RNDN);
		mpfr_set(x_6[0],x_6_p,GMP_RNDN);
		mpfr_set(x_7[0],x_7_p,GMP_RNDN);
		mpfr_set(x_8[0],x_8_p,GMP_RNDN);
		mpfr_set(x_9[0],x_9_p,GMP_RNDN);
		mpfr_set(x_10[0],x_10_p,GMP_RNDN);
		mpfr_set(x_11[0],x_11_p,GMP_RNDN);
		mpfr_set(x_12[0],x_12_p,GMP_RNDN);
		mpfr_set(x_13[0],x_13_p,GMP_RNDN);
		mpfr_set(x_14[0],x_14_p,GMP_RNDN);
		mpfr_set(x_15[0],x_15_p,GMP_RNDN);
		mpfr_set(x_16[0],x_16_p,GMP_RNDN);
		mpfr_set(x_17[0],x_17_p,GMP_RNDN);
		/*------------Taylor Series Method------------*/
		for (i = 0; i < order; i++){
			tsm_mul_cs(constant_1,x_5,saver_0,i);
			tsm_mul_cs(constant_1,x_1,saver_1,i);
			tsm_mul_cs(constant_1,x_3,saver_2,i);
			tsm_add_ss(x_11,saver_0,saver_3,i);
			tsm_add_ss(x_7,saver_1,saver_4,i);
			tsm_add_ss(x_9,saver_2,saver_5,i);
			tsm_add_ss(x_13,saver_1,saver_6,i);
			tsm_add_ss(x_15,saver_2,saver_7,i);
			tsm_add_ss(x_17,saver_0,saver_8,i);
			tsm_pow(saver_3,constant_0,saver_9,i);
			tsm_pow(saver_4,constant_0,saver_10,i);
			tsm_pow(saver_5,constant_0,saver_11,i);
			tsm_pow(saver_6,constant_0,saver_12,i);
			tsm_pow(saver_7,constant_0,saver_13,i);
			tsm_pow(saver_8,constant_0,saver_14,i);
			tsm_add_ss(saver_9,saver_10,saver_15,i);
			tsm_add_ss(saver_15,saver_11,saver_16,i);
			tsm_add_ss(saver_12,saver_13,saver_17,i);
			tsm_add_ss(saver_17,saver_14,saver_18,i);
			tsm_pow(saver_16,constant_2,saver_19,i);
			tsm_pow(saver_18,constant_2,saver_20,i);
			tsm_mul_cs(constant_3,saver_19,saver_21,i);
			tsm_mul_ss(saver_21,saver_4,saver_22,i);
			tsm_mul_cs(constant_3,saver_20,saver_23,i);
			tsm_mul_ss(saver_23,saver_6,saver_24,i);
			tsm_add_ss(saver_22,saver_24,saver_25,i);
			mpfr_set(saver_26[i], x_0[i], GMP_RNDN);
			tsm_mul_ss(saver_21,saver_5,saver_27,i);
			tsm_mul_ss(saver_23,saver_7,saver_28,i);
			tsm_add_ss(saver_27,saver_28,saver_29,i);
			mpfr_set(saver_30[i], x_2[i], GMP_RNDN);
			tsm_mul_ss(saver_21,saver_3,saver_31,i);
			tsm_mul_ss(saver_23,saver_8,saver_32,i);
			tsm_add_ss(saver_31,saver_32,saver_33,i);
			mpfr_set(saver_34[i], x_4[i], GMP_RNDN);
			tsm_mul_cs(constant_1,x_7,saver_35,i);
			tsm_mul_cs(constant_1,x_9,saver_36,i);
			tsm_mul_cs(constant_1,x_11,saver_37,i);
			tsm_add_ss(x_1,saver_35,saver_38,i);
			tsm_add_ss(x_3,saver_36,saver_39,i);
			tsm_add_ss(x_5,saver_37,saver_40,i);
			tsm_add_ss(x_13,saver_35,saver_41,i);
			tsm_add_ss(x_15,saver_36,saver_42,i);
			tsm_add_ss(x_17,saver_37,saver_43,i);
			tsm_pow(saver_38,constant_0,saver_44,i);
			tsm_pow(saver_39,constant_0,saver_45,i);
			tsm_pow(saver_40,constant_0,saver_46,i);
			tsm_pow(saver_41,constant_0,saver_47,i);
			tsm_pow(saver_42,constant_0,saver_48,i);
			tsm_pow(saver_43,constant_0,saver_49,i);
			tsm_add_ss(saver_44,saver_45,saver_50,i);
			tsm_add_ss(saver_50,saver_46,saver_51,i);
			tsm_add_ss(saver_47,saver_48,saver_52,i);
			tsm_add_ss(saver_52,saver_49,saver_53,i);
			tsm_pow(saver_51,constant_2,saver_54,i);
			tsm_pow(saver_53,constant_2,saver_55,i);
			tsm_mul_cs(constant_3,saver_54,saver_56,i);
			tsm_mul_ss(saver_56,saver_38,saver_57,i);
			tsm_mul_cs(constant_3,saver_55,saver_58,i);
			tsm_mul_ss(saver_58,saver_41,saver_59,i);
			tsm_add_ss(saver_57,saver_59,saver_60,i);
			mpfr_set(saver_61[i], x_6[i], GMP_RNDN);
			tsm_mul_ss(saver_56,saver_39,saver_62,i);
			tsm_mul_ss(saver_58,saver_42,saver_63,i);
			tsm_add_ss(saver_62,saver_63,saver_64,i);
			mpfr_set(saver_65[i], x_8[i], GMP_RNDN);
			tsm_mul_ss(saver_56,saver_40,saver_66,i);
			tsm_mul_ss(saver_58,saver_43,saver_67,i);
			tsm_add_ss(saver_66,saver_67,saver_68,i);
			mpfr_set(saver_69[i], x_10[i], GMP_RNDN);
			tsm_mul_cs(constant_1,x_13,saver_70,i);
			tsm_mul_cs(constant_1,x_15,saver_71,i);
			tsm_mul_cs(constant_1,x_17,saver_72,i);
			tsm_add_ss(x_1,saver_70,saver_73,i);
			tsm_add_ss(x_3,saver_71,saver_74,i);
			tsm_add_ss(x_5,saver_72,saver_75,i);
			tsm_add_ss(x_11,saver_72,saver_76,i);
			tsm_add_ss(x_7,saver_70,saver_77,i);
			tsm_add_ss(x_9,saver_71,saver_78,i);
			tsm_pow(saver_73,constant_0,saver_79,i);
			tsm_pow(saver_74,constant_0,saver_80,i);
			tsm_pow(saver_75,constant_0,saver_81,i);
			tsm_pow(saver_76,constant_0,saver_82,i);
			tsm_pow(saver_77,constant_0,saver_83,i);
			tsm_pow(saver_78,constant_0,saver_84,i);
			tsm_add_ss(saver_79,saver_80,saver_85,i);
			tsm_add_ss(saver_85,saver_81,saver_86,i);
			tsm_add_ss(saver_82,saver_83,saver_87,i);
			tsm_add_ss(saver_87,saver_84,saver_88,i);
			tsm_pow(saver_86,constant_2,saver_89,i);
			tsm_pow(saver_88,constant_2,saver_90,i);
			tsm_mul_cs(constant_3,saver_89,saver_91,i);
			tsm_mul_ss(saver_91,saver_73,saver_92,i);
			tsm_mul_cs(constant_3,saver_90,saver_93,i);
			tsm_mul_ss(saver_93,saver_77,saver_94,i);
			tsm_add_ss(saver_92,saver_94,saver_95,i);
			mpfr_set(saver_96[i], x_12[i], GMP_RNDN);
			tsm_mul_ss(saver_91,saver_74,saver_97,i);
			tsm_mul_ss(saver_93,saver_78,saver_98,i);
			tsm_add_ss(saver_97,saver_98,saver_99,i);
			mpfr_set(saver_100[i], x_14[i], GMP_RNDN);
			tsm_mul_ss(saver_91,saver_75,saver_101,i);
			tsm_mul_ss(saver_93,saver_76,saver_102,i);
			tsm_add_ss(saver_101,saver_102,saver_103,i);
			mpfr_set(saver_104[i], x_16[i], GMP_RNDN);
			mpfr_div_ui(x_0[i+1],saver_25[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_1[i+1],saver_26[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_2[i+1],saver_29[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_3[i+1],saver_30[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_4[i+1],saver_33[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_5[i+1],saver_34[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_6[i+1],saver_60[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_7[i+1],saver_61[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_8[i+1],saver_64[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_9[i+1],saver_65[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_10[i+1],saver_68[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_11[i+1],saver_69[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_12[i+1],saver_95[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_13[i+1],saver_96[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_14[i+1],saver_99[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_15[i+1],saver_100[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_16[i+1],saver_103[i],(i+1),GMP_RNDN);
			mpfr_div_ui(x_17[i+1],saver_104[i],(i+1),GMP_RNDN);
		}
		mpfr_abs(abs_tmp_1,x_0[0],GMP_RNDN);
		mpfr_abs(abs_tmp_2,x_1[0],GMP_RNDN);
		mpfr_max(max_M0, abs_tmp_1, abs_tmp_2, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_2[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_3[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_4[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_5[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_6[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_7[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_8[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_9[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_10[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_11[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_12[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_13[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_14[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_15[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_16[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_17[0],GMP_RNDN);
		mpfr_max(max_M0, max_M0, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_0[order-1],GMP_RNDN);
		mpfr_abs(abs_tmp_2,x_1[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, abs_tmp_1, abs_tmp_2, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_2[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_3[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_4[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_5[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_6[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_7[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_8[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_9[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_10[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_11[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_12[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_13[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_14[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_15[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_16[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_17[order-1],GMP_RNDN);
		mpfr_max(max_Mm1, max_Mm1, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_0[order],GMP_RNDN);
		mpfr_abs(abs_tmp_2,x_1[order],GMP_RNDN);
		mpfr_max(max_M, abs_tmp_1, abs_tmp_2, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_2[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_3[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_4[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_5[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_6[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_7[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_8[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_9[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_10[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_11[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_12[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_13[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_14[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_15[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_16[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		mpfr_abs(abs_tmp_1,x_17[order],GMP_RNDN);
		mpfr_max(max_M, max_M, abs_tmp_1, GMP_RNDN);
		if (mpfr_less_p(max_M0, one)){
			mpfr_log(rhom_1,max_Mm1,GMP_RNDN);
			mpfr_div_si(rhom_1,rhom_1,1-order,GMP_RNDN);
			mpfr_log(rhom_2,max_M,GMP_RNDN);
			mpfr_div_si(rhom_2,rhom_2,-order,GMP_RNDN);
			mpfr_min(rhom,rhom_1,rhom_2,GMP_RNDN);
		}
		else{
			mpfr_log(abs_tmp_1,max_M0,GMP_RNDN);
			mpfr_log(abs_tmp_2,max_Mm1,GMP_RNDN);
			mpfr_sub(rhom_1,abs_tmp_1,abs_tmp_2,GMP_RNDN);
			mpfr_div_si(rhom_1,rhom_1,order-1,GMP_RNDN);
			mpfr_log(abs_tmp_1,max_M0,GMP_RNDN);
			mpfr_log(abs_tmp_2,max_M,GMP_RNDN);
			mpfr_sub(rhom_2,abs_tmp_1,abs_tmp_2,GMP_RNDN);
			mpfr_div_si(rhom_2,rhom_1,order,GMP_RNDN);
			mpfr_min(rhom,rhom_1,rhom_2,GMP_RNDN);
		}
		mpfr_div_ui(inc_time,dotseven,1-order,GMP_RNDN);
		mpfr_sub_ui(inc_time,inc_time,2,GMP_RNDN);
		mpfr_add(inc_time,rhom,inc_time,GMP_RNDN);
		mpfr_exp(inc_time,inc_time,GMP_RNDN);
		fprint_flag = 0;
		mpfr_add(fake_time,t[0],inc_time,GMP_RNDN);
		if (mpfr_greater_p(fake_time, print_time)){
			mpfr_sub(inc_time, print_time, t[0], GMP_RNDN);
			mpfr_add(print_time, print_time, print_time_inc, GMP_RNDN);
			fprint_flag = 1;
			m = m + 1;
			T_s = m*print_time_d;
		}
		tsm_sum2(x_0, inc_time, x_0_p, order);
		tsm_sum2(x_1, inc_time, x_1_p, order);
		tsm_sum2(x_2, inc_time, x_2_p, order);
		tsm_sum2(x_3, inc_time, x_3_p, order);
		tsm_sum2(x_4, inc_time, x_4_p, order);
		tsm_sum2(x_5, inc_time, x_5_p, order);
		tsm_sum2(x_6, inc_time, x_6_p, order);
		tsm_sum2(x_7, inc_time, x_7_p, order);
		tsm_sum2(x_8, inc_time, x_8_p, order);
		tsm_sum2(x_9, inc_time, x_9_p, order);
		tsm_sum2(x_10, inc_time, x_10_p, order);
		tsm_sum2(x_11, inc_time, x_11_p, order);
		tsm_sum2(x_12, inc_time, x_12_p, order);
		tsm_sum2(x_13, inc_time, x_13_p, order);
		tsm_sum2(x_14, inc_time, x_14_p, order);
		tsm_sum2(x_15, inc_time, x_15_p, order);
		tsm_sum2(x_16, inc_time, x_16_p, order);
		tsm_sum2(x_17, inc_time, x_17_p, order);
		mpfr_add(t[0],t[0],inc_time,GMP_RNDN);
		if (fprint_flag){
		tsm_block_start(0);
		mpfr_fprintf(fp,"%.2Rf\t",t[0]);
		mpfr_fprintf(fp,"%1.200Re\t",x_0_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_1_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_2_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_3_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_4_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_5_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_6_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_7_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_8_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_9_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_10_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_11_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_12_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_13_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_14_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_15_p);
		mpfr_fprintf(fp,"%1.200Re\t",x_16_p);
		mpfr_fprintf(fp,"%1.200Re\n",x_17_p);
		tsm_block_end();
		}
	}
	tsm_clock_end();
	tsm_fina();
	return 0;
}
